# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-01 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0007_remove_done_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbIndexImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to=b'logo')),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_index_image',
                'managed': False,
            },
        ),
    ]
